[dependencies.Modbus-Custom-Device-PPL]
libraries = ['Modbus API.lvlibp']
copy_location = 'Source\Engine'

[projects.cd]
path = 'Source\Modbus Master Custom Device - Windows.lvproj'

[projects.cdLinux]
path = 'Source\Modbus Master Custom Device - Linux ARM.lvproj'

[projects.cdPharlap]
path = 'Source\Modbus Master Custom Device - RT PXI.lvproj'

[[build.steps]]
name = 'Configuration Library'
type = 'lvBuildSpec'
project = '{cd}'
target = 'My Computer'
build_spec = 'Configuration Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpecAllTargets'
project = '{cd}'
build_spec = 'Engine Release'

[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpec'
project = '{cdLinux}'
target = 'RT CompactRIO Target - Linux ARM'
build_spec = 'Engine Release'


[[build.steps]]
name = 'Engine Libraries'
type = 'lvBuildSpec'
project = '{cdPharlap}'
target = 'RT PXI Target'
build_spec = 'Engine Release'


[package]
type = 'nipkg'
name = 'modbus_master-{veristand_version}'
dev_xml_path = 'Source\Custom Device Modbus Master.xml'
install_destination = 'documents\National Instruments\NI VeriStand {veristand_version}'

[[release.steps]]
name = 'Master Release'
type = 'githubRelease'
2018_release_branches = ["master",]
2019_release_branches = ["master",]
2020_release_branches = ["master",]